testing

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -30,45 +30,45 @@ runs:
     - name: Scan for asset name from release
       shell: bash
       run: |
-        assetName=$(jq '.[] | select(.label | ascii_downcase | contains("${{inputs.release-asset-label-contains}}")) | .name' <<<'${{toJSON(github.event.release.assets)}}')
+        assetName=$(jq '.[] | select(.label | ascii_downcase | contains("helm chart")) | .name' <<<'${{toJSON(github.event.release.assets)}}')
         echo "assetName is $assetName"
-    - name: Scan for asset name from release
-      uses: sergeysova/jq-action@v2
-      id: assetName
-      with:
-        cmd: |
-          jq '.' <<<'${{toJSON(github.event.release.assets)}}'
+#    - name: Scan for asset name from release
+#      uses: sergeysova/jq-action@v2
+#      id: assetName
+#      with:
+#        cmd: |
+#          jq '.' <<<'${{toJSON(github.event.release.assets)}}'
 #          jq '. | select(.label | ascii_downcase | contains("${{inputs.release-asset-label-contains}}")) | .name' <<<${{toJSON(github.event.release.assets)}}
-    - name: Verify asset name
-      shell: bash
-      run: |
-        echo "asset name is  ${{ steps.assetName.outputs.value }}"
-        if [ -z ${{ steps.assetName.outputs.value }} ]; then
-          echo "Failed to find a release asset matching the configured label"
-          exit 1
-        fi
-    - name: Install Helm
-      uses: azure/setup-helm@v1
-      with:
-        version: v3.7.2
-    - name: Clone charts repository
-      uses: actions/checkout@v2
-      with:
-        token: ${{ inputs.token }}
-        repository: ${{ inputs.chart-repository }}
-        ref: ${{ inputs.chart-repository-ref }}
-    - name: Fetch release
-      uses: robinraju/release-downloader@v1.3
-      with:
-        repository: ${{ github.repository }}
-        tag: ${{ inputs.tag }}
-        fileName: ${{ inputs.release-asset-name }}
-        token: ${{ inputs.token }}
-    - name: Upload chart and reindex
-      shell: bash
-      run: |
-        tar -zxvf ${{ steps.assetName.outputs.value }} && rm ${{ steps.assetName.outputs.value }}
-        ls -l ${{ steps.assetName.outputs.value }}
+#    - name: Verify asset name
+#      shell: bash
+#      run: |
+#        echo "asset name is  ${{ steps.assetName.outputs.value }}"
+#        if [ -z ${{ steps.assetName.outputs.value }} ]; then
+#          echo "Failed to find a release asset matching the configured label"
+#          exit 1
+#        fi
+#    - name: Install Helm
+#      uses: azure/setup-helm@v1
+#      with:
+#        version: v3.7.2
+#    - name: Clone charts repository
+#      uses: actions/checkout@v2
+#      with:
+#        token: ${{ inputs.token }}
+#        repository: ${{ inputs.chart-repository }}
+#        ref: ${{ inputs.chart-repository-ref }}
+#    - name: Fetch release
+#      uses: robinraju/release-downloader@v1.3
+#      with:
+#        repository: ${{ github.repository }}
+#        tag: ${{ inputs.tag }}
+#        fileName: ${{ inputs.release-asset-name }}
+#        token: ${{ inputs.token }}
+#    - name: Upload chart and reindex
+#      shell: bash
+#      run: |
+#        tar -zxvf ${{ steps.assetName.outputs.value }} && rm ${{ steps.assetName.outputs.value }}
+#        ls -l ${{ steps.assetName.outputs.value }}
 #        helm repo index .
 #    - name: Commit changes
 #      uses: stefanzweifel/git-auto-commit-action@v4
